talaia-labs/python-teos

- teos/inspector.py
The signature checks in the Inspector were not enabled in #103. Fixing that.
> Adds missing inspector sig check from #103

- README.md
As described in #111, the paths of the generate keys example where wrong:
`~./teos` should have been `~/.teos`
> Fixes path typo on README

- test/cli/unit/test_teos_cli.py
It seems that the test for `test_get_appointment_err` was ignoring checking for `ConnectionError` as the mocked request was not actually polled by `teos_cli`, because the randomly generated locator was not added to the mocked request. 
This also fixes calling the `ConnectionError` function, which was unimported.
> cli: fixes testing for `ConnectionError` in `get_appointment`

- teos/responder.py
- teos/watcher.py
The last known block was not stored in the db for the `Watcher` and `Responder` on fresh bootstrap until a block was received. This caused problems if stopping the tower before hearing about a block, specially in testing.
Fixes #117
- Stores `last_known_block` in the db for both the `Watcher` and `Responder` on fresh bootstrap (before `do_watch` main loop)
- Adds `last_known_block` to `Watcher` to deal with forks in the future.
> Stores last block on db on fresh bootstrap for Watcher and Responder

- cli/teos_cli.py
- common/appointment.py
- requirements-dev.txt
- teos/api.py
- teos/extended_appointment.py
- teos/inspector.py
- teos/watcher.py
- test/cli/unit/test_teos_cli.py
- test/common/unit/test_appointment.py
- test/teos/e2e/test_basic_e2e.py
- test/teos/unit/conftest.py
- test/teos/unit/test_api.py
- test/teos/unit/test_extended_appointment.py
- test/teos/unit/test_inspector.py
- test/teos/unit/test_watcher.py
- watchtower-plugin/net/http.py
- watchtower-plugin/test_watchtower.py
- watchtower-plugin/watchtower.py
The current serialisation format for appointment signatures differ from the one in BOLT13 (`to_self_delay` and `encrypted_blob` are swapped). Moreover, for appointment accepted messages, the tower does not need to sign the same fields as the user plus the user signature, since signing the latter will implicitly include the former.
This PR modifies both serialisation formats as follows:
Appointment (signed by the user):
`locator | encrypted_blob | to_self_delay`
Receipt (signed by the tower) :
`user_signature | start_block`
Main changes:
`cli`:
- Splits the `add_appointment` method in two: `create_appointment` and `add_appointment`. Also adds stricter checks to the user provided data.
`cli` and `watchtower-plugin`:
- Updates the way the client side computes the data to verify the tower …
> Updates the serialisation format for appointment signatures

- cli/teos_cli.py
- common/appointment.py
- common/receipts.py
- common/tools.py
- teos/api.py
- teos/gatekeeper.py
- teos/watcher.py
- test/cli/unit/test_teos_cli.py
- test/common/unit/conftest.py
- test/common/unit/test_appointment.py
- test/common/unit/test_receipts.py
- test/common/unit/test_tools.py
- test/teos/e2e/test_basic_e2e.py
- test/teos/unit/test_api.py
- test/teos/unit/test_gatekeeper.py
- test/teos/unit/test_inspector.py
- test/teos/unit/test_watcher.py
- watchtower-plugin/net/http.py
- watchtower-plugin/retrier.py
- watchtower-plugin/test_watchtower.py
- watchtower-plugin/tower_info.py
- watchtower-plugin/towers_dbm.py
- watchtower-plugin/watchtower.py
Adds a tower signature to the missing tower responses that are not a `get_x` request. 
`get_x` responses are not signed since they do not imply any agreement between the user and the tower, so making sure the communication happens trough an authenticated channel should suffice. With respect to other requests (register, add_appointment, ...) they represent an agreement between the two parties. Therefore, misbehaving should be provable.
This PR removes the `create_receipt` method from `Appointment`, and creates a file in `common` called `receipts`. Given that multiple receipts may be needed (currently there are two: registration and add_appointment) and that the user and tower need to know exactly how to construct them, it seems better to have a single place for them.
Furthermore, since the …
> Sign all (non-get-x) tower responses

- requirements.txt
- teos/__init__.py
- teos/help.py
- teos/teosd.py
- test/teos/e2e/conftest.py
- test/teos/e2e/test_basic_e2e.py
Adds a "daemon" flag to the config that detaches the current shell in order to run in background.
Uses the [python-daemon](https://pypi.org/project/python-daemon/) library, which is therefore added to the requirements.
In this current version, there is no way to interact with the background daemon (for example to terminate it). That could be done together (or after) #146.
Closes: #172
> Adds a "daemon" flag

- test/teos/conftest.py
- test/teos/e2e/test_basic_e2e.py
- test/teos/unit/conftest.py
- test/teos/unit/test_api.py
- test/teos/unit/test_appointments_dbm.py
- test/teos/unit/test_builder.py
- test/teos/unit/test_chain_monitor.py
- test/teos/unit/test_cleaner.py
- test/teos/unit/test_gatekeeper.py
- test/teos/unit/test_inspector.py
- test/teos/unit/test_internal_api.py
- test/teos/unit/test_responder.py
- test/teos/unit/test_rpc.py
- test/teos/unit/test_tools.py
- test/teos/unit/test_watcher.py
Make the dependency to the run_bitcoind fixture explicit in tests that need it, so that unit tests can be ran individually.
This PR only takes care of the unit tests, not the e2e tests.
After that, 6 tests needed fixing as they functionally depended on the side effects of previous tests in the same test module:
- `test_get_appointment_in_watcher` and `test_get_appointment_in_responder` in test_api.py
- `test_delete_locator_map`, `test_delete_watcher_appointment` and `test_delete_responder_tracker` in test_appointments_dbm.py
- `test_do_watch_cache_update` in test_watcher.py
Fixed all of the above, except `test_do_watch_cache_update`: that is basically an integration test (together with the previous test, `test_do_watch`), so it might perhaps be better refactored out of the unit tests …
> Refactor tests so they can be ran individually

- .circleci/config.yml
Circle-ci cache was being dropped due to some permission errors with the `venv`. It seems it was due to upgrading pip with sudo.
Also activates the virtualenv properly before running the tests.
> Fix circleci cache

- teos/internal_api.py
- teos/rpc.py
- teos/teosd.py
Turns out gRPC in Python has some issues when using multiprocess. A way or working around it is to create the processes (fork) before instantiating anything related to gRPC.
This PR modifies the `InternalAPI` to be run in a similar way as the `RPC` does. Then the former is run in the main process but after the latter has been forked into a different process.
How the processes are handled have not changed from before (the main process takes care of the backend while the forked process takes care of the external RPC server).
Some info and related issues:
https://github.com/grpc/grpc/tree/b8241addc380e63b28be850c3da2fb04dc75212b/examples/python/multiprocessing
https://github.com/grpc/grpc/blob/master/doc/fork_support.md
https://github.com/grpc/grpc/issues/16001
> Fixes grpc with multiprocess

- teos/api.py
- teos/cli/help.py
- teos/cli/teos_cli.py
- teos/constants.py
- teos/internal_api.py
- teos/protobuf/protos/tower_services.proto
- teos/protobuf/tower_services_pb2.py
- teos/protobuf/tower_services_pb2_grpc.py
- teos/rpc.py
- teos/teosd.py
- test/teos/e2e/conftest.py
- test/teos/e2e/test_basic_e2e.py
- test/teos/unit/test_api.py
- test/teos/unit/test_internal_api.py
This pull request adds a `stop` command to teos_cli (and consequently to the RPC and the internal API).
Since the service is split among several threads and services, a clean teardown requires some synchronization among them, and services are stopped in the right order to avoid failing requests: public api first, internal rpc and internal api next. Whenever possible, some grace time is given to each service during shutdown.
It also refactors the teosd.py file, by moving all of the code that was in `main()` into a `TeosDaemon` class where it can be split into several methods. A further refactoring in order (possibly splitting the methods into even smaller method) to make the code testable would be a nice followup, but is left as future work.
Closes: #201, #80
> Add a "stop" command for graceful shutdown

- requirements-dev.txt
- teos/chain_monitor.py
- teos/responder.py
- teos/teosd.py
- teos/watcher.py
- test/teos/unit/test_chain_monitor.py
- test/teos/unit/test_responder.py
- test/teos/unit/test_watcher.py
Added a multi-state life-cycle to the ChainMonitor. Also generalized to accept an arbitrary number of subscribers, instead of the two that we're currently using.
It is IDLE when created, it listens but does not notifies subscribers when LISTENING, it listens and notifies subscribers when ACTIVE, it stop any actions when TERMINATED.
Also improved the shutdown code to properly wait for a graceful termination of Watcher and Responder threads.
Closes: #92
> Improve ChainMonitor to avoid missing blocks during bootstrap

- teos/api.py
- teos/cli/teos_cli.py
- teos/rpc.py
It looks like reusing the channel/stub is the correct way of making repeated grpc requests, as channels already support multiplexing concurrent requests on them.
This PR recycles the `stub` for the `API` class, and adds missing attribute docs for `_RPC`.
Closes: #193
> Modified API to reuse the grpc stub

- .circleci/config.yml
Currently circle-ci is building docker images for all the distros for every commit on master. This is due to how the circle-ci filters work (like an or statement instead of an and).
Removes the check of branch being master and leaves the tag conditions.
For reference: https://stackoverflow.com/questions/58792796/circleci-ignores-git-tag-filters
> Modifies circle-ci to run docker builds only on tags

- common/appointment.py
- common/cryptographer.py
- common/receipts.py
- contrib/client/teos_client.py
- teos/chain_monitor.py
- test/common/unit/test_appointment.py
- test/common/unit/test_receipts.py
- test/teos/e2e/test_basic_e2e.py
- test/teos/unit/test_api.py
- test/teos/unit/test_inspector.py
- test/teos/unit/test_internal_api.py
- watchtower-plugin/net/http.py
- watchtower-plugin/test_watchtower.py
binascii.{hexlify, unhexlify} are legacy functions that got built-ins in Python 3.5. Replacing all the instances.
The replacements are as follows:
`binascii.hexlify` --> `bytes.hex()`
`binascii.unhexlify` --> `bytes.from_hex()`
There are also some instances of `struck.pack` /  `struct.unpack` that were replaced for consistency:
`struct.pack(">I", x)` --> `x.to_bytes(4, 'big')`
`struct.unpack(">I", x)[0]` --> `int.from_bytes(x, 'big')`
Finally, the creation of `user_ids` in some tests have been simplified to use `Cryptographer.get_compressed_pk` instead duplicating code.
> Removes instances of binascii and struct

- teos/builder.py
- teos/extended_appointment.py
- teos/gatekeeper.py
- test/teos/unit/test_extended_appointment.py
I've tried to do a better job distinguishing between `Appointment` and `ExtendedAppointment`.
I haven't changed the `Watcher`'s code much since I didn't want to change `self.appointments` to `self.extended_appointments`.
All appointments within the tower are extended anyway, whereas they are not on the user-side.
> Distinguishes between appointment and extended_appointment

- common/appointment.py
- contrib/client/test/test_teos_client.py
- teos/api.py
- teos/chain_monitor.py
- teos/internal_api.py
- teos/responder.py
- teos/watcher.py
- test/common/unit/test_appointment.py
- test/teos/e2e/test_basic_e2e.py
- test/teos/unit/test_api.py
- test/teos/unit/test_chain_monitor.py
- watchtower-plugin/test_watchtower.py
- watchtower-plugin/tower_info.py
Adds an AppointmentStatus Enum for the possible appointment statuses, and a class constant for the "END" message of the ChainMonitor.
A larger refactoring in the same spirit could make sense for the config dictionary keys, but it is not trivial because of the need of making it work with `config_loader.py`.
Also fixing a few documentation errors and typos
Closes: 173
> Avoid hardcoded strings

- teos/api.py
- teos/cleaner.py
- teos/constants.py
- teos/gatekeeper.py
- teos/internal_api.py
- teos/responder.py
- teos/teosd.py
- teos/watcher.py
- test/teos/unit/test_api.py
- test/teos/unit/test_cleaner.py
- test/teos/unit/test_gatekeeper.py
- test/teos/unit/test_internal_api.py
- test/teos/unit/test_responder.py
- test/teos/unit/test_watcher.py
Expired subscriptions were not being checked when data was being sent by / requested from the tower. This PR handled that case and also moves the `UserInfo` deletion to the `Gatekeeper` instead of it being handled by either the `Watcher` or the `Responder`.
For this changes to work, the `Gatekeeper` now needs to have a notion of time, which is given by making him subscribe to the `ChainMonitor`. Also, data is being deleted with a `USERS_CACHE_SIZE_BLOCKS` delay so both the `Watcher` and the `Responder` can query any user related data they may need in order to do their own cleanups.
> Handles request rejection for expired subscriptions

- teos/api.py
- teos/constants.py
- teos/logger.py
- teos/rpc.py
- teos/teosd.py
The current hardcoded approach prevents a user from running multiple tower on the same host (for different networks for instance). With this approach the limitation is fixed.
Close #236
> Lets the OS pick a free port instead of harcoding one

- teos/api.py
One instance of `APPOINTMENT_INVALID_SIGNATURE_OR_INSUFFICIENT_SLOTS` was left after #239.
> Updates and old error type left after #239 was merged

- teos/gatekeeper.py
- teos/internal_api.py
- teos/responder.py
- teos/watcher.py
- test/teos/unit/test_gatekeeper.py
- test/teos/unit/test_responder.py
- test/teos/unit/test_watcher.py
This basically add RWLocks to:
- `Gatekeeper`
- `Responder`
- `Watcher`
Before this PR, the `InternalAPI` has a RWLock to guard the access to the backend. However, two threads are running for each of the main backend components (`Watcher` and `Responder`), meaning that, theoretically, their `do_watch` method could crash with the user data feeding (`add_appointment` and `handle_breach`). This tries to fix that.
For the `Gatekeeper`:
The writer lock is acquired for the data addition/update (`add_update_*` and `update_outdated_users_cache`) and deletion (`delete_appointments`). The reader lock is acquired for data querying (`authenticate_user`, `has_subscription_expired` and  `get_outdated_users`).
For the `Responder`:
The writer lock is acquired for `add_tracker` (called by `handle_breach`) …
> Reworks teos to use RWLocks

- teos/api.py
- teos/gunicorn_config.py
- teos/logger.py
- teos/teosd.py
Integrates the gunicorn and waitress logs with the logging server.
The approach is pretty straightforward, but a bit tricky. gunicorn allows a python config file to rewrite how it handles logs. The provided config file `gunicorn_conf.py` adds the timestamp and component to the message in a similar way used by `teos.logger`. The tricky parts comes with `SockerHandler`, since it does not use formatters. 
In order to work around it, `FormattedSocketHandler` is created inheriting from `SockerHandler` and applying the desired formatting before emitting the message. 
For waitress it is a bit easier, since `setup_logging` can be called. However, since it does not use `structlog` some additional config is needed to add the missing parts, in a similar fashion to `gunicorn` …
> Integrate wsgi logs

- .circleci/config.yml
Circle-ci was initially configured to build docker images tagged as `latest` every merge into master that was not tagged as a release, and tag with the release number for the ones that had one.
Later on it was modified to only build images for releases, given how long it takes to build the arm images. However, the latest tag part was not updated. Therefore, the `latest` tag was not being updated and builds that relayed on that were building with older versions, like `btcpay-server` docker builds.
This PR updates the circle-ci config to tag every release with the release number and tag it as latest.
Kudos to @whiteyhat for reporting the issue.
> Fixes circle ci latest tag on releases

- watchtower-plugin/test_watchtower.py
- Patches `test_watchtower_retry_offline` and `test_watchtower_no_slots` randomly failing due to requesting data back to the tower right after the payment was requested. Some times not all appointment were already on the tower making the final checks fail.
- Patches broken logs on the tower-covered node. Turns out giving up the backoff strategy currently issues a logging.error log (from `backoff`) that creates a broken log on c-lightning, that was making some tests fail. backoff has recently added the option to customise the log level for retries and give-ups, but it's not yet released. The plugin will need to be updated after the next release and the dependency version set. 
Related to #264
> Patches plugin tests randomly failing + broken logs

- test/teos/conftest.py
When I tried running the e2e tests, they would hang indefinitely. While debugging I found that bitcoind would get caught at bitcoin_cli.getnewaddress() in /test/teos/conftest.py, getting the error: `A default wallet is no longer automatically created`
I'm running version 0.21.0 of bitcoin, and it looks like in version 0.21.0 of bitcoind "Bitcoin Core will no longer automatically create new wallets on startup": https://lists.linuxfoundation.org/pipermail/bitcoin-core-dev/2021-January/000097.html
Proposing the following change, which allows tests to run smoothly while running the latest version of bitcoind
> Fix e2e tests so they work with bitcoind 0.21.0

- teos/logger.py
- teos/teosd.py
In some OSs teos was not showing logs if the system was not properly configured, due to it shutting down rather quickly. The root of the issue if the logging server shutting down before it has the chance of logging the info.
This commit syncs the shutting down process in case of an exception so the logging server can output properly.
Also simplifies the logging server (removes unnecessary methods, calls super properly, ...)
Fixes #278
> Fixes logs not showing if teos shutdowns right after start

- teos/teosd.py
Temporary fix for #246.
defaults GRPC_DNS_RESOLVER to native until a fix for https://github.com/grpc/grpc/issues/24018 is found.
> Patches #246

- teos/api.py
- teos/block_processor.py
- teos/carrier.py
- teos/chain_monitor.py
- teos/gatekeeper.py
- teos/internal_api.py
- teos/responder.py
- teos/teosd.py
- teos/watcher.py
- test/teos/unit/conftest.py
- test/teos/unit/test_api.py
- test/teos/unit/test_block_processor.py
- test/teos/unit/test_carrier.py
- test/teos/unit/test_chain_monitor.py
- test/teos/unit/test_gatekeeper.py
- test/teos/unit/test_internal_api.py
- test/teos/unit/test_responder.py
- test/teos/unit/test_watcher.py
The ChainMonitor polling thread now is also used to make sure bitcoind has not crashed. Locks have been added so the ChainMonitor thread can lock other background threads if bitcoind is down. This does not apply to user requests, since they need to give a timely response to the user.
In a nutshell, every time a thread makes a (blocking) call to bitcoind, if a `ConnectionRefusedError` is returned, the lock will be cleared and the function will be called recursively (this second time being blocked by the lock).
On the other hand, the `ChainMonitor` polling thread is the one in charge of setting the lock once the connection with bitcoind is reestablished, unblocking all other thread if applicable.
There are calls that should always be blocking, like the ones made by the `Carrier` or the ones …
> teos - Adds bitcoind polling to ensure it is alive

- watchtower-plugin/arg_parser.py
There was an edge case in `registertower` arg parsing where a trailing `:` will fail to parse.
Adds a special condition for that specific case.
> Plugin arg parser fix for registertower

- contrib/client/teos_client.py
- teos/cli/teos_cli.py
- teos/teosd.py
Capturing wrong options was moved out of the try/except in 3ea8806fcfcf2c4979bdd35bc4a6cebef8cb06b for teosd, making it fail if a wrong option was passed.
Partially addresses #283
> Fixes teosd getopt and adds more friendly output to teosd and cli

- common/config_loader.py
- contrib/client/teos_client.py
- teos/cli/teos_cli.py
- teos/template.conf
- teos/teosd.py
- test/common/unit/test_config_loader.py
- watchtower-plugin/watchtower.py
Unknown configuration values from the config file were ignored silently. From now on we'll report and refuse to run if any is found.
Partially addresses #283
> Refuse to run if unknown config parameters are found

- teos/appointments_dbm.py
- teos/cleaner.py
- teos/watcher.py
- test/teos/unit/mocks.py
- test/teos/unit/test_appointments_dbm.py
- test/teos/unit/test_cleaner.py
The `locator_uuid_map` of the `Watcher` was being backed up in the database but never being loaded (apart for the updating process) since the map is recreated on bootstrap from the appointment data.
The only benefit of storing the data is to prevent having to recreate the map on bootstrap (which was being done anyway) but it does make the tower to have to read and write data from/to the database way more constantly.
> Stops backing up the locator_uuid_map

- teos/cleaner.py
- teos/watcher.py
- test/teos/unit/test_cleaner.py
Both methods do the exact same, but the log messages are different.
close #288
> teos - Unifies delete_completed and delete_outdated appointments in the Cleaner

- test/teos/unit/test_watcher.py
#289 added new comparisons to Watcher.do_watch, but the one checking the content of the database should have been using sets, since the elements can be in different order.
> test - Fixes do_watch assert, cmp should be using sets

- .circleci/config.yml
bitcoin.org is getting DDosed recently so tests fail when trying to download the Bitcoin binaries for testing on circle-ci. Update the download link to bitcoincore.org.
> Updates circle-ci bitcoin download link to pull from bitcoincore.org

- docker/Dockerfile
As of containerd 1.4.6, the relative path in the volume will cause the container to not run
https://github.com/containerd/containerd/issues/5547
> Fix .teos volume path in Dockerfile

- .circleci/config.yml
The previously used image was deprecated, so updating to a newer ubuntu
version. This needs Python3.7 to be manually installed. Leaving it like
this for now, may be updated to reduce build times later on.
> Updates ubuntu image use by circle-ci

- common/requirements.txt
- setup.py
- test/teos/e2e/conftest.py
With this, the common package can be installed standalone. This is useful for testing against apps that get normally common from PyPi.
> Adds COMMON_ONLY option to setup.py

- watchtower-plugin/net/http.py
ReadTimeout was not taking into account when interacting with a tower (the timeout was set but the exception not properly catch). 
Sets different timeouts for connection and read timeouts. The read is significantly higher than the connection to account for slow connections (e.g. tor).
> Catches ReadTimeout in plugin/http
